project_name: opensips_exporter

builds:
  - id: opensips_exporter
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 5
      - 6
      - 7

checksum:
  name_template: "{{ .ProjectName }}_sha256sums.txt"
  algorithm: sha256

dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - opensips_exporter
    image_templates:
      - "voipgrid/opensips_exporter:{{ .Version }}"
      - "voipgrid/opensips_exporter:latest"
    skip_push: false
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    bindir: /usr/bin
    vendor: VoIPGRID
    homepage: https://www.voipgrid.nl
    maintainer: VoIPGRID <info@voipgrid.nl>
    license: Apache 2.0
    description: Simple server that scrapes OpenSIPS stats and exports them via HTTP for Prometheus consumption
    formats:
      - apk
      - deb
      - rpm

release:
  github:
    owner: voipgrid
    name: opensips_exporter
  prerelease: auto
